import Head from 'next/head'
import styles from '../styles/Home.module.css'
import HomePage from '../container/HomePage'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mentorship Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HomePage />
      </main>
    </div>
  )
}
