import Head from 'next/head'

export default function SignUp() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mentorship Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>Fresh Project</main>
    </div>
  )
}
